// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 03 Aug 2025 23:29:22 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <lgpio.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// lgGpioAlertsFunc_t_ef94f791 is a proxy for callback lgGpioAlertsFunc_t.
void lgGpioAlertsFunc_t_ef94f791(int num_alerts, struct lgGpioAlert_s* alerts, void* userdata);

// lgThreadFunc_t_4599736f is a proxy for callback lgThreadFunc_t.
void* lgThreadFunc_t_4599736f(void* arg0);

