// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 13 Aug 2025 17:09:29 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void* lgThreadFunc_t_4599736f(void* arg0) {
	return lgThreadFunc4599736F(arg0);
}

