// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 03 Aug 2025 23:29:22 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void lgGpioAlertsFunc_t_ef94f791(int num_alerts, struct lgGpioAlert_s* alerts, void* userdata) {
	lgGpioAlertsFuncEF94F791(num_alerts, alerts, userdata);
}

void* lgThreadFunc_t_4599736f(void* arg0) {
	return lgThreadFunc4599736F(arg0);
}

