// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 13 Aug 2025 17:09:29 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <lgpio.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// lgThreadFunc_t_4599736f is a proxy for callback lgThreadFunc_t.
void* lgThreadFunc_t_4599736f(void* arg0);

