// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 13 Aug 2025 17:09:29 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package lg

/*
#cgo LDFLAGS: -llgpio
#include <lgpio.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// LGPIO_H as defined in lggo/lgpio.h:29

	// LGPIO_VERSION as defined in lggo/lgpio.h:36
	LGPIO_VERSION = 0x00020200
	// LG_CD as defined in lggo/lgpio.h:38
	LG_CD = "LG_CD"
	// LG_WD as defined in lggo/lgpio.h:39
	LG_WD = "LG_WD"
	// LG_CFG_ID_DEBUG_LEVEL as defined in lggo/lgpio.h:220
	LG_CFG_ID_DEBUG_LEVEL = 0
	// LG_CFG_ID_MIN_DELAY as defined in lggo/lgpio.h:221
	LG_CFG_ID_MIN_DELAY = 1
	// LG_MAX_PATH as defined in lggo/lgpio.h:223
	LG_MAX_PATH = 1024
	// LG_THREAD_NONE as defined in lggo/lgpio.h:225
	LG_THREAD_NONE = 0
	// LG_THREAD_STARTED as defined in lggo/lgpio.h:226
	LG_THREAD_STARTED = 1
	// LG_THREAD_RUNNING as defined in lggo/lgpio.h:227
	LG_THREAD_RUNNING = 2
	// LG_NOTIFY_CLOSED as defined in lggo/lgpio.h:229
	LG_NOTIFY_CLOSED = 0
	// LG_NOTIFY_CLOSING as defined in lggo/lgpio.h:230
	LG_NOTIFY_CLOSING = 1
	// LG_NOTIFY_RUNNING as defined in lggo/lgpio.h:231
	LG_NOTIFY_RUNNING = 2
	// LG_NOTIFY_PAUSED as defined in lggo/lgpio.h:232
	LG_NOTIFY_PAUSED = 3
	// LG_USER_LEN as defined in lggo/lgpio.h:241
	LG_USER_LEN = 16
	// LG_SALT_LEN as defined in lggo/lgpio.h:242
	LG_SALT_LEN = 16
	// LG_FILE_NONE as defined in lggo/lgpio.h:247
	LG_FILE_NONE = 0
	// LG_FILE_MIN as defined in lggo/lgpio.h:248
	LG_FILE_MIN = 1
	// LG_FILE_READ as defined in lggo/lgpio.h:249
	LG_FILE_READ = 1
	// LG_FILE_WRITE as defined in lggo/lgpio.h:250
	LG_FILE_WRITE = 2
	// LG_FILE_RW as defined in lggo/lgpio.h:251
	LG_FILE_RW = 3
	// LG_FILE_APPEND as defined in lggo/lgpio.h:252
	LG_FILE_APPEND = 4
	// LG_FILE_CREATE as defined in lggo/lgpio.h:253
	LG_FILE_CREATE = 8
	// LG_FILE_TRUNC as defined in lggo/lgpio.h:254
	LG_FILE_TRUNC = 16
	// LG_FILE_MAX as defined in lggo/lgpio.h:255
	LG_FILE_MAX = 31
	// LG_FROM_START as defined in lggo/lgpio.h:257
	LG_FROM_START = 0
	// LG_FROM_CURRENT as defined in lggo/lgpio.h:258
	LG_FROM_CURRENT = 1
	// LG_FROM_END as defined in lggo/lgpio.h:259
	LG_FROM_END = 2
	// LG_GPIO_LABEL_LEN as defined in lggo/lgpio.h:264
	LG_GPIO_LABEL_LEN = 32
	// LG_GPIO_NAME_LEN as defined in lggo/lgpio.h:265
	LG_GPIO_NAME_LEN = 32
	// LG_GPIO_USER_LEN as defined in lggo/lgpio.h:266
	LG_GPIO_USER_LEN = 32
	// LG_GPIO_IS_KERNEL as defined in lggo/lgpio.h:270
	LG_GPIO_IS_KERNEL = 1
	// LG_GPIO_IS_OUTPUT as defined in lggo/lgpio.h:271
	LG_GPIO_IS_OUTPUT = 2
	// LG_GPIO_IS_ACTIVE_LOW as defined in lggo/lgpio.h:272
	LG_GPIO_IS_ACTIVE_LOW = 4
	// LG_GPIO_IS_OPEN_DRAIN as defined in lggo/lgpio.h:273
	LG_GPIO_IS_OPEN_DRAIN = 8
	// LG_GPIO_IS_OPEN_SOURCE as defined in lggo/lgpio.h:274
	LG_GPIO_IS_OPEN_SOURCE = 16
	// LG_GPIO_IS_PULL_UP as defined in lggo/lgpio.h:275
	LG_GPIO_IS_PULL_UP = 32
	// LG_GPIO_IS_PULL_DOWN as defined in lggo/lgpio.h:276
	LG_GPIO_IS_PULL_DOWN = 64
	// LG_GPIO_IS_PULL_NONE as defined in lggo/lgpio.h:277
	LG_GPIO_IS_PULL_NONE = 128
	// LG_GPIO_IS_INPUT as defined in lggo/lgpio.h:279
	LG_GPIO_IS_INPUT = 65536
	// LG_GPIO_IS_RISING_EDGE as defined in lggo/lgpio.h:280
	LG_GPIO_IS_RISING_EDGE = 131072
	// LG_GPIO_IS_FALLING_EDGE as defined in lggo/lgpio.h:281
	LG_GPIO_IS_FALLING_EDGE = 262144
	// LG_GPIO_IS_REALTIME_CLOCK as defined in lggo/lgpio.h:282
	LG_GPIO_IS_REALTIME_CLOCK = 524288
	// LG_RISING_EDGE as defined in lggo/lgpio.h:286
	LG_RISING_EDGE = 1
	// LG_FALLING_EDGE as defined in lggo/lgpio.h:287
	LG_FALLING_EDGE = 2
	// LG_BOTH_EDGES as defined in lggo/lgpio.h:288
	LG_BOTH_EDGES = 3
	// LG_SET_ACTIVE_LOW as defined in lggo/lgpio.h:292
	LG_SET_ACTIVE_LOW = 4
	// LG_SET_OPEN_DRAIN as defined in lggo/lgpio.h:293
	LG_SET_OPEN_DRAIN = 8
	// LG_SET_OPEN_SOURCE as defined in lggo/lgpio.h:294
	LG_SET_OPEN_SOURCE = 16
	// LG_SET_PULL_UP as defined in lggo/lgpio.h:295
	LG_SET_PULL_UP = 32
	// LG_SET_PULL_DOWN as defined in lggo/lgpio.h:296
	LG_SET_PULL_DOWN = 64
	// LG_SET_PULL_NONE as defined in lggo/lgpio.h:297
	LG_SET_PULL_NONE = 128
	// LG_SET_REALTIME_CLOCK as defined in lggo/lgpio.h:301
	LG_SET_REALTIME_CLOCK = 256
	// LG_SET_INPUT as defined in lggo/lgpio.h:302
	LG_SET_INPUT = 512
	// LG_SET_OUTPUT as defined in lggo/lgpio.h:303
	LG_SET_OUTPUT = 1024
	// LG_LOW as defined in lggo/lgpio.h:307
	LG_LOW = 0
	// LG_HIGH as defined in lggo/lgpio.h:308
	LG_HIGH = 1
	// LG_TIMEOUT as defined in lggo/lgpio.h:309
	LG_TIMEOUT = 2
	// LG_TX_PWM as defined in lggo/lgpio.h:311
	LG_TX_PWM = 0
	// LG_TX_WAVE as defined in lggo/lgpio.h:312
	LG_TX_WAVE = 1
	// LG_MAX_MICS_DEBOUNCE as defined in lggo/lgpio.h:314
	LG_MAX_MICS_DEBOUNCE = 5000000
	// LG_MAX_MICS_WATCHDOG as defined in lggo/lgpio.h:315
	LG_MAX_MICS_WATCHDOG = 300000000
	// LG_MAX_MICS_DELAY as defined in lggo/lgpio.h:320
	LG_MAX_MICS_DELAY = 5e6
	// LG_MAX_MILS_DELAY as defined in lggo/lgpio.h:321
	LG_MAX_MILS_DELAY = 300e6
	// LG_SCRIPT_INITING as defined in lggo/lgpio.h:326
	LG_SCRIPT_INITING = 0
	// LG_SCRIPT_READY as defined in lggo/lgpio.h:327
	LG_SCRIPT_READY = 1
	// LG_SCRIPT_RUNNING as defined in lggo/lgpio.h:328
	LG_SCRIPT_RUNNING = 2
	// LG_SCRIPT_WAITING as defined in lggo/lgpio.h:329
	LG_SCRIPT_WAITING = 3
	// LG_SCRIPT_EXITED as defined in lggo/lgpio.h:330
	LG_SCRIPT_EXITED = 4
	// LG_SCRIPT_ENDED as defined in lggo/lgpio.h:331
	LG_SCRIPT_ENDED = 5
	// LG_SCRIPT_HALTED as defined in lggo/lgpio.h:332
	LG_SCRIPT_HALTED = 6
	// LG_SCRIPT_FAILED as defined in lggo/lgpio.h:333
	LG_SCRIPT_FAILED = 7
	// LG_MAX_SPI_DEVICE_COUNT as defined in lggo/lgpio.h:338
	LG_MAX_SPI_DEVICE_COUNT = (1 << 16)
	// LG_I2C_RDRW_IOCTL_MAX_MSGS as defined in lggo/lgpio.h:345
	LG_I2C_RDRW_IOCTL_MAX_MSGS = 42
	// LG_MAX_I2C_DEVICE_COUNT as defined in lggo/lgpio.h:347
	LG_MAX_I2C_DEVICE_COUNT = (1 << 16)
	// LG_MAX_I2C_ADDR as defined in lggo/lgpio.h:348
	LG_MAX_I2C_ADDR = 0x7F
	// LG_I2C_END as defined in lggo/lgpio.h:352
	LG_I2C_END = 0
	// LG_I2C_ESC as defined in lggo/lgpio.h:353
	LG_I2C_ESC = 1
	// LG_I2C_ADDR as defined in lggo/lgpio.h:354
	LG_I2C_ADDR = 2
	// LG_I2C_FLAGS as defined in lggo/lgpio.h:355
	LG_I2C_FLAGS = 3
	// LG_I2C_READ as defined in lggo/lgpio.h:356
	LG_I2C_READ = 4
	// LG_I2C_WRITE as defined in lggo/lgpio.h:357
	LG_I2C_WRITE = 5
	// LG_OKAY as defined in lggo/lgpio.h:2873
	LG_OKAY = 0
	// LG_INIT_FAILED as defined in lggo/lgpio.h:2874
	LG_INIT_FAILED = -1
	// LG_BAD_MICROS as defined in lggo/lgpio.h:2875
	LG_BAD_MICROS = -2
	// LG_BAD_PATHNAME as defined in lggo/lgpio.h:2876
	LG_BAD_PATHNAME = -3
	// LG_NO_HANDLE as defined in lggo/lgpio.h:2877
	LG_NO_HANDLE = -4
	// LG_BAD_HANDLE as defined in lggo/lgpio.h:2878
	LG_BAD_HANDLE = -5
	// LG_BAD_SOCKET_PORT as defined in lggo/lgpio.h:2879
	LG_BAD_SOCKET_PORT = -6
	// LG_NOT_PERMITTED as defined in lggo/lgpio.h:2880
	LG_NOT_PERMITTED = -7
	// LG_SOME_PERMITTED as defined in lggo/lgpio.h:2881
	LG_SOME_PERMITTED = -8
	// LG_BAD_SCRIPT as defined in lggo/lgpio.h:2882
	LG_BAD_SCRIPT = -9
	// LG_BAD_TX_TYPE as defined in lggo/lgpio.h:2883
	LG_BAD_TX_TYPE = -10
	// LG_GPIO_IN_USE as defined in lggo/lgpio.h:2884
	LG_GPIO_IN_USE = -11
	// LG_BAD_PARAM_NUM as defined in lggo/lgpio.h:2885
	LG_BAD_PARAM_NUM = -12
	// LG_DUP_TAG as defined in lggo/lgpio.h:2886
	LG_DUP_TAG = -13
	// LG_TOO_MANY_TAGS as defined in lggo/lgpio.h:2887
	LG_TOO_MANY_TAGS = -14
	// LG_BAD_SCRIPT_CMD as defined in lggo/lgpio.h:2888
	LG_BAD_SCRIPT_CMD = -15
	// LG_BAD_VAR_NUM as defined in lggo/lgpio.h:2889
	LG_BAD_VAR_NUM = -16
	// LG_NO_SCRIPT_ROOM as defined in lggo/lgpio.h:2890
	LG_NO_SCRIPT_ROOM = -17
	// LG_NO_MEMORY as defined in lggo/lgpio.h:2891
	LG_NO_MEMORY = -18
	// LG_SOCK_READ_FAILED as defined in lggo/lgpio.h:2892
	LG_SOCK_READ_FAILED = -19
	// LG_SOCK_WRIT_FAILED as defined in lggo/lgpio.h:2893
	LG_SOCK_WRIT_FAILED = -20
	// LG_TOO_MANY_PARAM as defined in lggo/lgpio.h:2894
	LG_TOO_MANY_PARAM = -21
	// LG_SCRIPT_NOT_READY as defined in lggo/lgpio.h:2895
	LG_SCRIPT_NOT_READY = -22
	// LG_BAD_TAG as defined in lggo/lgpio.h:2896
	LG_BAD_TAG = -23
	// LG_BAD_MICS_DELAY as defined in lggo/lgpio.h:2897
	LG_BAD_MICS_DELAY = -24
	// LG_BAD_MILS_DELAY as defined in lggo/lgpio.h:2898
	LG_BAD_MILS_DELAY = -25
	// LG_I2C_OPEN_FAILED as defined in lggo/lgpio.h:2899
	LG_I2C_OPEN_FAILED = -26
	// LG_SERIAL_OPEN_FAILED as defined in lggo/lgpio.h:2900
	LG_SERIAL_OPEN_FAILED = -27
	// LG_SPI_OPEN_FAILED as defined in lggo/lgpio.h:2901
	LG_SPI_OPEN_FAILED = -28
	// LG_BAD_I2C_BUS as defined in lggo/lgpio.h:2902
	LG_BAD_I2C_BUS = -29
	// LG_BAD_I2C_ADDR as defined in lggo/lgpio.h:2903
	LG_BAD_I2C_ADDR = -30
	// LG_BAD_SPI_CHANNEL as defined in lggo/lgpio.h:2904
	LG_BAD_SPI_CHANNEL = -31
	// LG_BAD_I2C_FLAGS as defined in lggo/lgpio.h:2905
	LG_BAD_I2C_FLAGS = -32
	// LG_BAD_SPI_FLAGS as defined in lggo/lgpio.h:2906
	LG_BAD_SPI_FLAGS = -33
	// LG_BAD_SERIAL_FLAGS as defined in lggo/lgpio.h:2907
	LG_BAD_SERIAL_FLAGS = -34
	// LG_BAD_SPI_SPEED as defined in lggo/lgpio.h:2908
	LG_BAD_SPI_SPEED = -35
	// LG_BAD_SERIAL_DEVICE as defined in lggo/lgpio.h:2909
	LG_BAD_SERIAL_DEVICE = -36
	// LG_BAD_SERIAL_SPEED as defined in lggo/lgpio.h:2910
	LG_BAD_SERIAL_SPEED = -37
	// LG_BAD_FILE_PARAM as defined in lggo/lgpio.h:2911
	LG_BAD_FILE_PARAM = -38
	// LG_BAD_I2C_PARAM as defined in lggo/lgpio.h:2912
	LG_BAD_I2C_PARAM = -39
	// LG_BAD_SERIAL_PARAM as defined in lggo/lgpio.h:2913
	LG_BAD_SERIAL_PARAM = -40
	// LG_I2C_WRITE_FAILED as defined in lggo/lgpio.h:2914
	LG_I2C_WRITE_FAILED = -41
	// LG_I2C_READ_FAILED as defined in lggo/lgpio.h:2915
	LG_I2C_READ_FAILED = -42
	// LG_BAD_SPI_COUNT as defined in lggo/lgpio.h:2916
	LG_BAD_SPI_COUNT = -43
	// LG_SERIAL_WRITE_FAILED as defined in lggo/lgpio.h:2917
	LG_SERIAL_WRITE_FAILED = -44
	// LG_SERIAL_READ_FAILED as defined in lggo/lgpio.h:2918
	LG_SERIAL_READ_FAILED = -45
	// LG_SERIAL_READ_NO_DATA as defined in lggo/lgpio.h:2919
	LG_SERIAL_READ_NO_DATA = -46
	// LG_UNKNOWN_COMMAND as defined in lggo/lgpio.h:2920
	LG_UNKNOWN_COMMAND = -47
	// LG_SPI_XFER_FAILED as defined in lggo/lgpio.h:2921
	LG_SPI_XFER_FAILED = -48
	// LG_BAD_POINTER as defined in lggo/lgpio.h:2922
	LG_BAD_POINTER = -49
	// LG_MSG_TOOBIG as defined in lggo/lgpio.h:2923
	LG_MSG_TOOBIG = -50
	// LG_BAD_MALLOC_MODE as defined in lggo/lgpio.h:2924
	LG_BAD_MALLOC_MODE = -51
	// LG_TOO_MANY_SEGS as defined in lggo/lgpio.h:2925
	LG_TOO_MANY_SEGS = -52
	// LG_BAD_I2C_SEG as defined in lggo/lgpio.h:2926
	LG_BAD_I2C_SEG = -53
	// LG_BAD_SMBUS_CMD as defined in lggo/lgpio.h:2927
	LG_BAD_SMBUS_CMD = -54
	// LG_BAD_I2C_WLEN as defined in lggo/lgpio.h:2928
	LG_BAD_I2C_WLEN = -55
	// LG_BAD_I2C_RLEN as defined in lggo/lgpio.h:2929
	LG_BAD_I2C_RLEN = -56
	// LG_BAD_I2C_CMD as defined in lggo/lgpio.h:2930
	LG_BAD_I2C_CMD = -57
	// LG_FILE_OPEN_FAILED as defined in lggo/lgpio.h:2931
	LG_FILE_OPEN_FAILED = -58
	// LG_BAD_FILE_MODE as defined in lggo/lgpio.h:2932
	LG_BAD_FILE_MODE = -59
	// LG_BAD_FILE_FLAG as defined in lggo/lgpio.h:2933
	LG_BAD_FILE_FLAG = -60
	// LG_BAD_FILE_READ as defined in lggo/lgpio.h:2934
	LG_BAD_FILE_READ = -61
	// LG_BAD_FILE_WRITE as defined in lggo/lgpio.h:2935
	LG_BAD_FILE_WRITE = -62
	// LG_FILE_NOT_ROPEN as defined in lggo/lgpio.h:2936
	LG_FILE_NOT_ROPEN = -63
	// LG_FILE_NOT_WOPEN as defined in lggo/lgpio.h:2937
	LG_FILE_NOT_WOPEN = -64
	// LG_BAD_FILE_SEEK as defined in lggo/lgpio.h:2938
	LG_BAD_FILE_SEEK = -65
	// LG_NO_FILE_MATCH as defined in lggo/lgpio.h:2939
	LG_NO_FILE_MATCH = -66
	// LG_NO_FILE_ACCESS as defined in lggo/lgpio.h:2940
	LG_NO_FILE_ACCESS = -67
	// LG_FILE_IS_A_DIR as defined in lggo/lgpio.h:2941
	LG_FILE_IS_A_DIR = -68
	// LG_BAD_SHELL_STATUS as defined in lggo/lgpio.h:2942
	LG_BAD_SHELL_STATUS = -69
	// LG_BAD_SCRIPT_NAME as defined in lggo/lgpio.h:2943
	LG_BAD_SCRIPT_NAME = -70
	// LG_CMD_INTERRUPTED as defined in lggo/lgpio.h:2944
	LG_CMD_INTERRUPTED = -71
	// LG_BAD_EVENT_REQUEST as defined in lggo/lgpio.h:2945
	LG_BAD_EVENT_REQUEST = -72
	// LG_BAD_GPIO_NUMBER as defined in lggo/lgpio.h:2946
	LG_BAD_GPIO_NUMBER = -73
	// LG_BAD_GROUP_SIZE as defined in lggo/lgpio.h:2947
	LG_BAD_GROUP_SIZE = -74
	// LG_BAD_LINEINFO_IOCTL as defined in lggo/lgpio.h:2948
	LG_BAD_LINEINFO_IOCTL = -75
	// LG_BAD_READ as defined in lggo/lgpio.h:2949
	LG_BAD_READ = -76
	// LG_BAD_WRITE as defined in lggo/lgpio.h:2950
	LG_BAD_WRITE = -77
	// LG_CANNOT_OPEN_CHIP as defined in lggo/lgpio.h:2951
	LG_CANNOT_OPEN_CHIP = -78
	// LG_GPIO_BUSY as defined in lggo/lgpio.h:2952
	LG_GPIO_BUSY = -79
	// LG_GPIO_NOT_ALLOCATED as defined in lggo/lgpio.h:2953
	LG_GPIO_NOT_ALLOCATED = -80
	// LG_NOT_A_GPIOCHIP as defined in lggo/lgpio.h:2954
	LG_NOT_A_GPIOCHIP = -81
	// LG_NOT_ENOUGH_MEMORY as defined in lggo/lgpio.h:2955
	LG_NOT_ENOUGH_MEMORY = -82
	// LG_POLL_FAILED as defined in lggo/lgpio.h:2956
	LG_POLL_FAILED = -83
	// LG_TOO_MANY_GPIOS as defined in lggo/lgpio.h:2957
	LG_TOO_MANY_GPIOS = -84
	// LG_UNEGPECTED_ERROR as defined in lggo/lgpio.h:2958
	LG_UNEGPECTED_ERROR = -85
	// LG_BAD_PWM_MICROS as defined in lggo/lgpio.h:2959
	LG_BAD_PWM_MICROS = -86
	// LG_NOT_GROUP_LEADER as defined in lggo/lgpio.h:2960
	LG_NOT_GROUP_LEADER = -87
	// LG_SPI_IOCTL_FAILED as defined in lggo/lgpio.h:2961
	LG_SPI_IOCTL_FAILED = -88
	// LG_BAD_GPIOCHIP as defined in lggo/lgpio.h:2962
	LG_BAD_GPIOCHIP = -89
	// LG_BAD_CHIPINFO_IOCTL as defined in lggo/lgpio.h:2963
	LG_BAD_CHIPINFO_IOCTL = -90
	// LG_BAD_CONFIG_FILE as defined in lggo/lgpio.h:2964
	LG_BAD_CONFIG_FILE = -91
	// LG_BAD_CONFIG_VALUE as defined in lggo/lgpio.h:2965
	LG_BAD_CONFIG_VALUE = -92
	// LG_NO_PERMISSIONS as defined in lggo/lgpio.h:2966
	LG_NO_PERMISSIONS = -93
	// LG_BAD_USERNAME as defined in lggo/lgpio.h:2967
	LG_BAD_USERNAME = -94
	// LG_BAD_SECRET as defined in lggo/lgpio.h:2968
	LG_BAD_SECRET = -95
	// LG_TX_QUEUE_FULL as defined in lggo/lgpio.h:2969
	LG_TX_QUEUE_FULL = -96
	// LG_BAD_CONFIG_ID as defined in lggo/lgpio.h:2970
	LG_BAD_CONFIG_ID = -97
	// LG_BAD_DEBOUNCE_MICS as defined in lggo/lgpio.h:2971
	LG_BAD_DEBOUNCE_MICS = -98
	// LG_BAD_WATCHDOG_MICS as defined in lggo/lgpio.h:2972
	LG_BAD_WATCHDOG_MICS = -99
	// LG_BAD_SERVO_FREQ as defined in lggo/lgpio.h:2973
	LG_BAD_SERVO_FREQ = -100
	// LG_BAD_SERVO_WIDTH as defined in lggo/lgpio.h:2974
	LG_BAD_SERVO_WIDTH = -101
	// LG_BAD_PWM_FREQ as defined in lggo/lgpio.h:2975
	LG_BAD_PWM_FREQ = -102
	// LG_BAD_PWM_DUTY as defined in lggo/lgpio.h:2976
	LG_BAD_PWM_DUTY = -103
	// LG_GPIO_NOT_AN_OUTPUT as defined in lggo/lgpio.h:2977
	LG_GPIO_NOT_AN_OUTPUT = -104
	// LG_INVALID_GROUP_ALERT as defined in lggo/lgpio.h:2978
	LG_INVALID_GROUP_ALERT = -105
)

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
