// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 03 Aug 2025 22:32:30 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lg provides Go bindings for lgpiod.
*/
package lg
