// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 13 Aug 2025 17:09:29 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package lg provides Go bindings for lgpiod.
*/
package lg
