// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 13 Aug 2025 17:09:29 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package lg

/*
#cgo LDFLAGS: -llgpio
#include <lgpio.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// LgChipInfo as declared in lggo/lgpio.h:367
type LgChipInfo struct {
	Lines          uint32
	Name           [32]byte
	Label          [32]byte
	refa740d20d    *C.lgChipInfo_t
	allocsa740d20d interface{}
}

// LgNotify as declared in lggo/lgpio.h:375
type LgNotify struct {
	State          uint16
	Fd             int32
	Pipe_number    int32
	Max_emits      int32
	ref7a0dd963    *C.lgNotify_t
	allocs7a0dd963 interface{}
}

// LgGpioReport as declared in lggo/lgpio.h:386
type LgGpioReport struct {
	Timestamp      uint64
	Chip           byte
	Gpio           byte
	Level          byte
	Flags          byte
	ref36aaf007    *C.lgGpioReport_t
	allocs36aaf007 interface{}
}

// LgLineInfo as declared in lggo/lgpio.h:400
type LgLineInfo struct {
	Offset         uint32
	LFlags         uint32
	Name           [32]byte
	User           [32]byte
	ref7e1327b3    *C.lgLineInfo_t
	allocs7e1327b3 interface{}
}

// LgPulse as declared in lggo/lgpio.h:407
type LgPulse struct {
	Bits           uint64
	Mask           uint64
	Delay          int64
	refff55d232    *C.lgPulse_t
	allocsff55d232 interface{}
}

// LgI2cMsg as declared in lggo/lgpio.h:415
type LgI2cMsg struct {
	Addr           uint16
	Flags          uint16
	Len            uint16
	Buf            []byte
	ref6927ca3d    *C.lgI2cMsg_t
	allocs6927ca3d interface{}
}

// LgThreadFunc type as declared in lggo/lgpio.h:423
type LgThreadFunc func(arg0 unsafe.Pointer) unsafe.Pointer
